services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
      - ../tests:/app/tests
    working_dir: /app
    environment:
      - PYTHONFAULTHANDLER=1
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=random
    restart: unless-stopped
    command: bash -c "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  test:
    container_name: test
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    volumes:
      - ../app:/app/app
      - ../tests:/app/tests
    working_dir: /app
    command: bash -c "tail -f /dev/null"